# https://webdriver.io/docs/githubactions
name: CI

on: [push]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup NPM
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install NPM
          run: npm install
        - name: Test
          run: npm run wdio:githubaction
        - name: Upload Report
          uses: actions/upload-artifact@v3
          # if: failure()
          with:
            name: allure
            path: ./reports/allure/allure-report