# https://webdriver.io/docs/githubactions
name: Web - CI - Every push
# on:[push, pull_request]
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup NPM
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install NPM
          run: npm install

        - name: Test
          run: npm run wdio:githubaction env=qa browser=chrome
          # continue-on-error: true

        - name: Upload Report
          uses: actions/upload-artifact@v3
          # if: failure()
          with:
            name: allure
            path: ./reports/allure/allure-report
